name: "snyk"
version: "1.2.1"
usage: "Check images in your charts for vulnerabilities"
description: |-
  "Test your helm charts' docker images with Snyk"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"

ignoreFlags: false
useTunnel: false
